version: '3.8'

services:
#   frontend:
#     build:
#       context: ./managment-user-front
#       dockerfile: Dockerfile
#     ports:
#       - "80:80"
#     depends_on:
#       - backend
#     environment:
#       - REACT_APP_API_URL=http://localhost:3000

#   backend:
#     build:
#       context: ./managment-user-api
#       dockerfile: Dockerfile
#     ports:
#       - "3000:3000"
#     depends_on:
#       - postgres
#     environment:
#       - DATABASE_HOST=postgres
#       - DATABASE_PORT=5432
#       - DATABASE_USERNAME=postgres
#       - DATABASE_PASSWORD=postgres
#       - DATABASE_NAME=management_app
#       - JWT_SECRET=your-super-secret-key-here
#       - JWT_EXPIRATION=1d

  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=management_app
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./managment-user-api/src/database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: 